MoviesBooks/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.home, name="home"),
    path("api/", include('api.urls')),
    path("movies/", include('movies.urls')),
    path("books/", include('books.urls')),
]

api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.api_info, name="api_info"),
    path("movies/", views.similar_movies, name="similar_movies"),
    path("books/", views.similar_books, name="similar_books"),
]

books/urls.py
from django.urls import path
from . import views


app_name = "books"

urlpatterns = [
    path("", views.books_recommendations_search,
         name="books_recommendations_search"),
    path("found/", views.get_books, name="get_books")
]

movies/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "movies"

urlpatterns = [
    path("", views.movies_recommendations_search,
         name="movies_recommendations_search"),
]

api/models.py
from django.db import models

# Create your models here.

books/models.py
from django.db import models

# Create your models here.

movies/models.py
from django.db import models

# Create your models here.

MoviesBooks/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'home.html')

api/views.py
from django.shortcuts import render
from rest_framework.decorators import api_view
from rest_framework.response import Response

# Create your views here.


@api_view(['GET'])
def similar_movies(request):
    query = request.GET.get('title', '')
    movies = [
        {'title': 'Inception', 'year': 2010},
        {'title': 'Interstellar', 'year': 2010},
        {'title': 'Tenet', 'year': 2010},
    ]

    return Response({
        'results': movies
    })


def api_info(request):
    return render(request, 'api_info.html')


@api_view(['GET'])
def similar_books(request):
    query = request.GET.get('title', '')
    books = [
        {'title': 'Harry Potter', 'year': 2010},
        {'title': 'Lord of the Rings', 'year': 2010},
        {'title': 'The Witcher', 'year': 2010},
    ]

    return Response({
        'results': books
    })

books/views.py
from django.shortcuts import render
import requests
from dotenv import load_dotenv
import os


# Create your views here.
load_dotenv()

key = os.getenv("API_KEY")

def books_recommendations_search(request):
    return render(request, "books/search_book.html")


def get_books(request):
    query = request.GET.get('title')
    API_KEY = key
    url = "https://www.googleapis.com/books/v1/volumes"
    params = {
        "q": query,
        "key": API_KEY,
        "maxResults": 10
    }

    response = requests.get(url, params=params)
    data = response.json()
    books = data.get('items', [])

    return render(request, 'books/books_found.html', {'books': books})

movies/views.py
from django.shortcuts import render

# Create your views here.


def movies_recommendations_search(request):
    return render(request, "movies/search_movie.html")

api/templates/api_info.html
{% extends "layout.html" %}


{% block title %}
API usage
{% endblock %}
    
{% block body %}
<h3>Get movies API </h3>
<p>Endpoint should end like this: api/movies/</p>
<h3>Get books API </h3>
<p>Endpoint should end like this: api/books/</p>
{% endblock %}
    

books/templates/books/books_found.html
{% extends "layout.html" %}


{% block title %}
Found books
{% endblock %}
    
{% block body %}
<div class="results">
    {% for book in books%}

        <h2>{{ book.volumeInfo.title }}</h2>
        <p>Written by: {{ book.volumeInfo.authors|join:", "|default:"Unknown" }}</p>
        <p>Published in: {{ book.volumeInfo.publishedDate|default:"Unknown" }}</p>
        <p>By: {{ book.volumeInfo.publisher|default:"Unknown" }}</p>
        <p>Description: {{ book.volumeInfo.description|default:"Unknown" }}</p>

    {% empty %}

        <p>No books found. Check if spelling is correct.</p>

    {% endfor %}


</div>   
{% endblock %}
    

books/templates/books/search_book.html
{% extends "layout.html" %}


{% block title %}
Recommendations for books
{% endblock %}
    
{% block body %}
<div class="search">
    <form method="GET" action="{% url 'books:get_books' %}">
        <input type="text" id="search" name="title" placeholder="Start typing book title">
        <button type="submit">Search</button>
    </form>
    <div id="results"></div>
</div>   
{% endblock %}
    

movies/templates/movies/search_movie.html
{% extends "layout.html" %}


{% block title %}
Recommendations for movies
{% endblock %}
    
{% block body %}
<div class="search">
    <form method="GET" action="#">
        <input type="text" id="search" name="title" placeholder="Start typing movie title">
        <button type="submit">Search</button>
    </form>
    <div id="results"></div>
</div>   
{% endblock %}
    

templates/home.html
{% extends "layout.html" %}


{% block title %}
Movies and books recommendations
{% endblock %}
    
{% block body %}
<div class="options-container">
    <a class='main-choice' href='movies/'>
        <h1 class="option">Movies</h1>
    </a>
    <a class='main-choice' href='books/'>
    <h1 class="option">Books</h1>
    </a>
</div>   
{% endblock %}
    

templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
        Movies and books recommendations
        {% endblock %}   
    </title>

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block head %}
    
    {% endblock %}
</head>
<body>
    <nav>
        <a href="/" class="choice">
            <span role="img" aria-label="Home" title="Home">🏠</span>
        </a>
        <a href="/movies" class="choice">
            <span role="text" aria-label="Movies" title="Movies">Movies</span>
        </a>
        <a href="/books" class="choice">
            <span role="text" aria-label="Books" title="Books">Books</span>
        </a>
    </nav>
    {% block body %}
    
    {% endblock  %}
</body>
</html>